TRUNCATE users CASCADE;
ALTER SEQUENCE users_id_seq RESTART WITH 1;

TRUNCATE tokens CASCADE;

TRUNCATE activities CASCADE;
ALTER SEQUENCE activities_id_seq RESTART WITH 1;

TRUNCATE routes CASCADE;
ALTER SEQUENCE routes_id_seq RESTART WITH 1;

TRUNCATE sports CASCADE;
ALTER SEQUENCE sports_id_seq RESTART WITH 1;
